graph LR

fitz2009continuous
claps2015journey
olsson2012climbing
chen2015towards
bosch2014continuous
liu2014integrated
forsgren2015role
neely2013continuous
itkonen2016perceived
chen2015continuous
fowler2013continuous
humble2010continuous

claps2015journey --> fitz2009continuous
itkonen2016perceived --> chen2015continuous
itkonen2016perceived --> fowler2013continuous
itkonen2016perceived --> humble2010continuous
