graph LR

a(CI/CD)

a---vcs(Version Control)
a---cis(Build/CI-server)
a---repo(Artifact Repository)
a---qa(Quality Analysis)
a---fr(Functional Tests)
a---d(Deployment Server)



vcs---Subversion
cis---Jenkins
repo---Nexus
qa---Sonar
fr---Selenium
